/*

Generate the appropriate fragment for the current form, then
wrap the main Form component with the necessary HoCs while passing 
them the fragment. 

This component is itself wrapped with:

- withCurrentUser
- withApollo (used to access the Apollo client for form pre-population)

And wraps the Form component with:

- withNew

Or: 

- withSingle
- withUpdate
- withDelete

(When wrapping with withSingle, withUpdate, and withDelete, a special Loader
component is also added to wait for withSingle's loading prop to be false)

*/

import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { intlShape } from 'meteor/vulcan:i18n';
import { withRouter } from 'react-router';
import { withApollo, compose } from 'react-apollo';
import {
  Components,
  registerComponent,
  withCurrentUser,
  Utils,
  withNew,
  withUpdate,
  withDelete,
  getFragment,
} from 'meteor/vulcan:core';
import gql from 'graphql-tag';
import { withSingle } from 'meteor/vulcan:core';
import { graphql } from 'react-apollo';

import withCollectionProps from './withCollectionProps';
import { callbackProps } from './propTypes';

import getFormFragments from '../modules/formFragments';

class FormWrapper extends PureComponent {
  constructor(props) {
    super(props);
  }
  UNSAFE_componentWillMount() {
    // instantiate the wrapped component outside of render
    // see https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method
    this.FormComponent = this.getComponent(this.props);
  }
  UNSAFE_componentWillReceiveProps(nextProps) {
    // reset if a documentId has been added or removed
    const shouldReset =
      (nextProps.documentId && !this.props.documentId) ||
      (!nextProps.documentId && this.props.documentId);
    // reinit the component on certain props change
    if (shouldReset) {
      this.FormComponent = this.getComponent(nextProps);
    }
  }
  // return the current schema based on either the schema or collection prop
  getSchema(props) {
    return props.schema ? props.schema : props.collection.simpleSchema()._schema;
  }

  // if a document is being passed, this is an edit form
  getFormType(props) {
    return props.documentId || props.slug ? 'edit' : 'new';
  }

  // get fragment used to decide what data to load from the server to populate the form,
  // as well as what data to ask for as return value for the mutation
  getFragments(props) {
    const { fields, addFields, typeName, collectionName } = props;
    // autogenerated fragments
    let { queryFragment, mutationFragment, extraQueries } = getFormFragments({
      formType: this.getFormType(props),
      collectionName,
      typeName,
      schema: this.getSchema(props),
      fields,
      addFields,
    });

    // if queryFragment or mutationFragment props are specified, accept either fragment object or fragment string
    if (props.queryFragment) {
      queryFragment =
        typeof props.queryFragment === 'string'
          ? gql`
              ${props.queryFragment}
            `
          : props.queryFragment;
    }
    if (props.mutationFragment) {
      mutationFragment =
        typeof props.mutationFragment === 'string'
          ? gql`
              ${props.mutationFragment}
            `
          : props.mutationFragment;
    }

    // same with queryFragmentName and mutationFragmentName
    if (props.queryFragmentName) {
      queryFragment = getFragment(props.queryFragmentName);
    }
    if (props.mutationFragmentName) {
      mutationFragment = getFragment(props.mutationFragmentName);
    }

    // get query & mutation fragments from props or else default to same as generatedFragment
    return {
      queryFragment,
      mutationFragment,
      extraQueries,
    };
  }

  getComponent(props) {
    const formType = this.getFormType(props);
    let WrappedComponent;

    const prefix = `${props.collectionName}${Utils.capitalize(formType)}`;

    const { queryFragment, mutationFragment, extraQueries } = this.getFragments(props);

    // props to pass on to child component (i.e. <Form />)
    const childProps = {
      formType,
      schema: this.getSchema(props),
    };

    // options for withSingle HoC
    const queryOptions = {
      queryName: `${prefix}FormQuery`,
      collection: props.collection,
      fragment: queryFragment,
      extraQueries,
      fetchPolicy: 'network-only', // we always want to load a fresh copy of the document
      enableCache: false,
      pollInterval: 0, // no polling, only load data once
    };

    // options for withNew, withUpdate, and withDelete HoCs
    const mutationOptions = {
      collection: props.collection,
      fragment: mutationFragment,
    };

    // create a stateless loader component,
    // displays the loading state if needed, and passes on loading and document/data
    const Loader = props => {
      const { document, loading } = props;
      return loading ? (
        <Components.Loading />
      ) : (
        <Components.Form document={document} loading={loading} {...childProps} {...props} />
      );
    };
    Loader.displayName = 'withLoader(Form)';

    // if this is an edit from, load the necessary data using the withSingle HoC
    if (formType === 'edit') {
      WrappedComponent = compose(
        withSingle(queryOptions),
        withUpdate(mutationOptions),
        withDelete(mutationOptions)
      )(Loader);

      return (
        <WrappedComponent
          selector={{
            documentId: props.documentId,
            slug: props.slug,
          }}
        />
      );
    } else {
      if (extraQueries && extraQueries.length) {
        const extraQueriesHoC = graphql(
          gql`
          query formNewExtraQuery {
            ${extraQueries}
          }`,
          {
            alias: 'withExtraQueries',
            props: returnedProps => {
              const { /* ownProps, */ data } = returnedProps;
              const props = {
                loading: data.loading,
                data,
              };
              return props;
            },
          }
        );

        WrappedComponent = compose(
          extraQueriesHoC,
          withNew(mutationOptions)
        )(Loader);
      } else {
        WrappedComponent = compose(withNew(mutationOptions))(Components.Form);
      }

      return <WrappedComponent {...childProps} />;
    }
  }

  render() {
    const component = this.FormComponent;
    const componentWithParentProps = React.cloneElement(component, this.props);
    return componentWithParentProps;
  }
}

FormWrapper.propTypes = {
  // main options
  collection: PropTypes.object.isRequired,
  collectionName: PropTypes.string.isRequired,
  typeName: PropTypes.string.isRequired,

  documentId: PropTypes.string, // if a document is passed, this will be an edit form
  schema: PropTypes.object, // usually not needed
  queryFragment: PropTypes.object,
  queryFragmentName: PropTypes.string,
  mutationFragment: PropTypes.object,
  mutationFragmentName: PropTypes.string,

  // graphQL
  newMutation: PropTypes.func, // the new mutation
  editMutation: PropTypes.func, // the edit mutation
  removeMutation: PropTypes.func, // the remove mutation

  // form
  prefilledProps: PropTypes.object,
  layout: PropTypes.string,
  fields: PropTypes.arrayOf(PropTypes.string),
  hideFields: PropTypes.arrayOf(PropTypes.string),
  addFields: PropTypes.arrayOf(PropTypes.string),
  showRemove: PropTypes.bool,
  submitLabel: PropTypes.node,
  cancelLabel: PropTypes.node,
  revertLabel: PropTypes.node,
  repeatErrors: PropTypes.bool,
  warnUnsavedChanges: PropTypes.bool,

  // callbacks
  ...callbackProps,

  currentUser: PropTypes.object,
  client: PropTypes.object,
};

FormWrapper.defaultProps = {
  layout: 'horizontal',
};

FormWrapper.contextTypes = {
  closeCallback: PropTypes.func,
  intl: intlShape,
};

registerComponent({
  name: 'SmartForm',
  component: FormWrapper,
  hocs: [withCurrentUser, withApollo, withRouter, withCollectionProps],
});
